Added the logic of required 4 requirements
jAlpedrinha/de-coding-test-mohammed-khan pull request #1
Opened 2024-06-15 17:45 UTC by arifkhan09

![Image 15-06-2024 at 18 44](https://github.com/jAlpedrinha/de-coding-test-mohammed-khan/assets/45659415/ea33530d-e85b-4667-9dba-d939117134d7)
Journeys of 90 minutes or more.
![Image 15-06-2024 at 18 44](https://github.com/jAlpedrinha/de-coding-test-mohammed-khan/assets/45659415/7e939b5c-d884-4b73-ba6e-99200e31c38e)

This journey took longer than 90 minutes
000008,driver_e,1633436902000,1633429702000,0.125,0.458,0.129,0.558,123360,123371

Average speeds in Kph.
000003,driver_b,1633429702000,1633430302000,0.123,0.456,0.124,0.457,123456,123459 avgSpeed in kph was 1.6983300405049828
000007,driver_d,1633429702000,1633436902000,0.125,0.458,0.129,0.558,923360,123371 avgSpeed in kph was 10.015466636516335
000002,driver_a,1633430310000,1633433910000,0.124,0.457,0.125,0.458,123459,123500 avgSpeed in kph was 0.2830549894303009
000005,driver_b,1633430362000,1633430422000,0.125,0.458,0.125,0.458,123460,123461 avgSpeed in kph was 0.0
000001,driver_a,1633429702000,1633430302000,0.123,0.456,0.124,0.457,123456,123459 avgSpeed in kph was 1.6983300405049828
000002,driver_a,1633430310000,1633433910000,0.124,0.457,0.125,0.458,123459,123500 avgSpeed in kph was 0.2830549894303009
000008,driver_e,1633436902000,1633429702000,0.125,0.458,0.129,0.558,123360,123371 avgSpeed in kph was 0.0
000006,driver_c,1633429702000,1633436902000,0.125,0.458,0.129,0.558,123360,123471 avgSpeed in kph was 10.015466636516335
000004,driver_b,1633430302000,1633430362000,0.124,0.457,0.125,0.458,123459,123460 avgSpeed in kph was 16.983299365818052

Mileage By Driver.
driver_e drove 11 kilometers
driver_c drove 111 kilometers
driver_b drove 5 kilometers
driver_a drove 44 kilometers

Most active driver...
Most active driver is driver_c

Process finished with exit code 0

2024-06-17 17:10 UTC, jAlpedrinha requested changes
Glad to read your code, hope you had fun ! As part of the challenge I've added a few comments and suggestions as would happen on a regular PR.

The goal is to address some of the comments and do a new commit if you're able to. After that we'll score your solution.

2024-06-17 17:10 UTC, jAlpedrinha commented on src/main/java/ai/humn/telematics/ProcessDataFile.scala
> +    var results = ListBuffer[Array[String]]()
Could we eventually use a better structure to store the Journeys rather than `Array[String]` ?

2024-06-17 17:10 UTC, jAlpedrinha commented on src/main/java/ai/humn/telematics/ProcessDataFile.scala
> +    while (ok) {
While this was on the original junior dev code, would there be a better of iterating through the journey list ?

2024-06-17 17:10 UTC, jAlpedrinha commented on src/main/java/ai/humn/telematics/ProcessDataFile.scala
> +  def haversine(lat1:Double,lon1:Double,lat2:Double,lon2:Double):Double={
While this is quite impressive, there is a way to know the exact distance for each trip from the input data.

Maybe it's worth checking the readme's description of the input data.

2024-06-18 08:19 UTC, closed without merging

2024-06-18 08:19 UTC, arifkhan09 commented
create a new PR so close this PR